# Site wide configuration

title:            Polar Clouds
locale:           en_GB
url:		  http://polarclouds.co.uk


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Chris Hall
  avatar: ch200x200.jpg
  bio: "I like to adjust technology to make it fit my requirements.<br><br>Windows, Linux, Virtualisation, Unified Computing & Cloud Offerings Design Engineer."
  email:
  disqus-shortname:
  twitter: PolarCloudsUK
  facebook: #username
  google:
    plus: u/0/103894884565976994275
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: chall32
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
